name: river-levels

channels:
  - esri
  - conda-forge

dependencies:
  - beautifulsoup4
  - arcgis
  - pandas
  - pip
  - python=3.7
  - python-dateutil
  - python-dotenv
  - pytz
  - requests
  - pip:
      - tsmoothie
